library(dplyr)
library(ggplot2)
library(rpart)
ucla = read.csv('https://stats.idre.ucla.edu/stat/data/binary.csv')
ucla$admit = factor(ucla$admit)
install.packages("survival")
library(survival)
install.packages("randomForest")
library(randomForest)
install.packages("e1071")
library(e1071)
s1 = svm(admit~., data = ucla)
r1 = rpart(admit~., data=ucla)
f1 = randomForest(admit~., data = ucla)
table(predict(s1, ucla, type = 'class'), ucla$admit)
table(predict(r1, ucla, type = 'class'), ucla$admit)
table(predict(f1, ucla, type = 'class'), ucla$admit)

clean_colon = na.omit(colon)
clean_colon = clean_colon[c(TRUE, FALSE), ]
clean_colon$status = factor(clean_colon$status)
s2 = svm(status~rx + sex + age + obstruct + perfor + adhere + nodes + differ + extent + surg + node4, data = clean_colon)
r2 = rpart(status~rx + sex + age + obstruct + perfor + adhere + nodes + differ + extent + surg + node4, data = clean_colon)
f2 = randomForest(status~rx + sex + age + obstruct + perfor + adhere + nodes + differ + extent + surg + node4, data = clean_colon)
table(predict(s2, clean_colon, type = 'class'), clean_colon$status)
table(predict(r2, clean_colon, type = 'class'), clean_colon$status)
table(predict(f2, clean_colon, type = 'class'), clean_colon$status)
voice = read.csv('C:/Sources/voice.csv')

s3 = svm(label~., data = voice)
r3 = rpart(label~., data = voice)
f3 = randomForest(label~., data = voice)

table(predict(s3, voice, type = 'class'), voice$label)
table(predict(r3, voice, type = 'class'), voice$label)
table(predict(f3, voice, type = 'class'), voice$label)

