beer = scan()
barplot(beer)
barplot(table(beer))
barplot(table(beer)/length(beer))
table(beer)/length(beer)
beer.counts = table(beer)
pie(beer.counts)
names(beer.counts) = c("domestic\n can", "Domestic\n bottle", "import \can", "microbrewed")
pie(beer.counts)
pie(beer.counts,col=c("purple","green2","cyan","white"))
