adultFemale=read.csv("literacy_rate_adult_female_percent_of_females_ages_15_above.csv",header=TRUE,sep=",")
adultMale=read.csv("literacy_rate_adult_male_percent_of_males_ages_15_and_above.csv", header=TRUE, sep=",")
adultTotal = read.csv("literacy_rate_adult_total_percent_of_people_ages_15_and_above.csv", header=TRUE, sep = ",")
youthFemale = read.csv("literacy_rate_youth_female_percent_of_females_ages_15_24.csv", header = TRUE, sep=",")
youthMale = read.csv("literacy_rate_youth_male_percent_of_males_ages_15_24.csv", header=TRUE, sep=",")
youthTotal = read.csv("literacy_rate_youth_total_percent_of_people_ages_15_24.csv", header = TRUE, sep=",")

install.packages("tidyr")
library(tidyr)
adultFemale_tidy=gather(adultFemale, -country, key="year", value="adult_female")
adultMale_tidy=gather(adultMale, -country, key="year", value="adult_male")
adultTotal_tidy = gather(adultTotal, -country, key="year", value="adult_total")
youthFemale_tidy=gather(youthFemale, -country, key="year", value="youth_female")
youthMale_tidy=gather(youthMale, -country, key="year", value="youth_male")
youthTotal_tidy=gather(youthTotal, -country, key="year", value="youth_total")
literacy = merge(adultFemale_tidy, adultMale_tidy)
literacy = merge(literacy, adultMale_tidy)
literacy = merge(literacy, adultTotal_tidy)
literacy = merge(literacy, youthFemale_tidy)
literacy = merge(literacy, youthMale_tidy)
literacy = merge(literacy, youthTotal_tidy)
literacy = na.omit(literacy)

literacy
