library(ggplot2)
library(dplyr)
install.packages("rpart")
library(rpart)
r=rpart(Species~Petal.Width+Sepal.Length+Sepal.Width,data=iris)
par(mfrow=c(1,1), xpd=NA)
plot(r)
text(r,use.n=TRUE)
p=predict(r, iris,type='class')
table(p,iris$Species)